genres = [
  "Advertising",
  "Alternative",
  "Ambient",
  "Anti-Folk",
  "Audiobook",
  "Avant-Garde",
  "Blues",
  "Christmas",
  "Classical",
  "Comedy",
  "Cosmiche",
  "Country",
  "Disco",
  "Drama",
  "Dubstep",
  "Easy Listening",
  "Electroclash",
  "Electronic",
  "Experimental",
  "Field Recording",
  "Folk-Rock",
  "Folk",
  "Funk",
  "Garage",
  "Goth",
  "Grindcore",
  "Grunge",
  "Hauntology",
  "Hip-Hop",
  "Indie",
  "Indiepop",
  "Industrial",
  "Japanese Hawaiian",
  "Jazz",
  "Latin",
  "Lo-Fi",
  "Lounge",
  "Math-Rock",
  "Minimalist",
  "Modern Classical",
  "Motown",
  "New Wave",
  "Noise",
  "Northern Soul",
  "Novelty",
  "Oi",
  "Pop",
  "Post-Punk",
  "Post-Rock",
  "Progressive Rock",
  "Psychedelic",
  "Psychobilly",
  "Punk",
  "Reggae",
  "Riot Grrrl",
  "Rock and Roll",
  "Rock",
  "Shoegaze",
  "Slowcore",
  "Soul",
  "Soundtrack",
  "Space-Rock",
  "Spazzcore",
  "Spoken Word",
  "Synthpop",
  "Toy Orchestra",
  "Trip-Hop",
  "Unclassifiable",
  "Unknown",
]

[ignore]
syncflac = ["/storage/flac/new"]

[ignore.lint]
invalid_title_tag = [
  "albums/abc/azusa_plane.where_the_sands_turn_to_gold/disc_2/09.azusa_plane.she_was_into_sandm_and_bible_studies_not_everyones_cup_of_tea_she_would_admit_to_me_her_cup_of_tea_she_would_admit_to_no_one",
  "albums/abc/bablicon.in_a_different_city/04.bablicon.star_semicolon_bang_colon_dash",
  "albums/def/delta_72.the_rnb_of_membership/09.delta_72.7_and_7",
  "albums/pqrs/roger_species.bad_taste/44.roger_species.jisjkfjncsdc",
  "albums/wxyz/wallpaper.honing_the_spectacular/13.wallpaper.alcohol_pcp_and_dollars",
]

invalid_album_tag = [
  "albums/def/delta_72.the_rnb_of_membership/",
  "eps/abc/annie.the_a_and_r_ep/",
]

invalid_artist_tag = [
  "christmas/albums/various.24/08.l_and_m_kingsize.we_ruined_xmas",
]

invalid_directory_name = ["albums/pqrs/reynols.______"]

invalid_year_tag = ["tracks"]

invalid_filename = [
  "albums/abc/apples_in_stereo.tone_soul_evolution--2017_remaster/02.apples_in_stereo.whats_the_number",
  "albums/abc/awesome.the_fact_and_the_fiction/13.awesome.dollar_from_home",
  "albums/jkl/jeffrey_lewis.2021_tapes--suddenly_its_been_too_late_for_a_long_time/10.jeffrey_lewis.black_lives_matter--dollar-hat-at-star-hash_that--black_power",
  "albums/various/various.before_the_fall/18.tommy_blake.f-oldin_money",
  "albums/various/various.rough_trade_shops-electronic_01/disc_1/17.aphex_twin.inkey-dollar",
  "albums/wxyz/wallpaper.honing_the_spectacular/13.wallpaper.alcohol_pcp_and_dollars",
  "christmas/albums/various.24/08.l_and_m_kingsize.we_ruined_xmas",
]

[ignore.lintdir]
inconsistent_tags = [
  "albums/abc/annie.dj_kicks",
  "albums/abc/cassetteboy_vs_dj_rubbish.inside_a_whales_cock",
  "albums/abc/cassetteboy.micks_tape",
  "albums/abc/cub.mauler",
  "albums/def/ersatz_titanium_pizza.emergency_exit",
  "albums/def/flowchart.pre-2000_singles_and_comp_tracks_part_one",
  "albums/def/frank_sidebottom.medium_play",
  "albums/jkl/jon_brooks.applied_music_vol_2--plastics_today",
  "albums/jkl/k-l-f.solid_state_logik_1",
  "albums/jkl/k-l-f.solid_state_logik_2",
  "albums/jkl/luke_haines.luke_haines_is_dead/",
  "albums/mno/mamas_and_the_papas.the_best_of_the_mamas_and_the_papas",
  "albums/mno/max_richter.the_blue_notebooks--15_years",
  "albums/mno/monochrome_set.eligible_bachelors--deluxe_edition/disc_3",
  "albums/mno/of_montreal.covers",
  "albums/pqrs/pet_shop_boys.disco_2",
  "albums/pqrs/pet_shop_boys.disco_4",
  "albums/pqrs/pet_shop_boys.disco_5",
  "albums/pqrs/quintron.spellcaster_ii--death_in_space",
  "albums/pqrs/richard_cheese.the_lounge_awakens",
  "albums/pqrs/sly_and_the_family_stone.higher",
  "albums/tuv/talking_heads.bonus_tracks",
  "albums/tuv/thee_headcoats.elementary_headcoats/",
  "albums/tuv/u2.rattle_and_hum",
  "audiobooks/john_le_carre.george_smiley",
  "audiobooks/agatha_christie.bbc_radio_4--hercule_poirot",
  "christmas/albums/v-vm.the_v-vm_christmas_pudding",
  "christmas/eps/v-vm.whine_and_missingtoe",
  "christmas/eps/yellow6.merry6mas2007",
  "eps/def/ersatz_titanium_pizza.unfit_for_human_consumption",
  "eps/jkl/lavender_diamond.open_your_heart",
  "radio_sessions/quickspace.peel_sessions",
  "radio_shows/bbc_radio_4.sherlock_holmes/",
  "radio_shows/chris_morris.glr_show",
  "radio_shows/chris_morris.no_known_cure",
  "radio_shows/frank_sidebottom.manchester_radio_online",
  "spoken_word/agatha_christie.bbc_radio_4--hercule_poirot",
  "spoken_word/frank_sidebottom.radio_timperley",
  "spoken_word/john_le_carre.george_smiley",
]

bad_file_count = [
  "albums/abc/cracker.kerosene_hat",
  "albums/pqrs/stone_roses.second_coming",
]

[ignore.wantflac]
top_level = [
  "audiobooks",
  "christmas/spackers",
  "eps/various/various.polyvinyl_4_track_singles_series",
  "hi-fi_stuf",
  "language",
  "new",
  "radio_sessions",
  "radio_shows",
  "spoken_word",
]

albums = [
  "albums/abc/apples_in_stereo.tone_soul_evolution--2017_remaster",
  "albums/abc/bags.all_bagged_up_77-80",
  "albums/abc/bip_ling.church_of_bop",
  "albums/def/david_barnes.whats_weird--audio_commentary",
  "albums/def/frank_sidebottom.13-9-88",
  "albums/abc/cheap_red.no_bs_just_ts",
  "albums/def/frank_sidebottom.5-9-88",
  "albums/def/frank_sidebottom.medium_play",
  "albums/ghi/great_lakes.contenders",
  "albums/ghi/happy_flowers.making_the_bunny_pay",
  "albums/ghi/harry_burns.a_love_affair_with_harry_burns",
  "albums/jkl/kyron.ascending_plume_of_faces",
  "albums/jkl/locust.the_peel_sessions",
  "albums/jkl/joe_jack_talcum.home_recordings_1984-1990",
  "albums/jkl/joe_jack_talcum.home_recordings_1993-1999",
  "albums/mno/my_bloody_valentine.loveless--8kbps",
  "albums/mno/neutral_milk_hotel.beauty",
  "albums/mno/new_bad_things.off_the_leash",
  "albums/mno/of_montreal.covers ",
  "albums/mno/of_montreal.false_priest--pre_jon_brion",
  "albums/mno/of_montreal.young_froth--taypiss",
  "albums/pqrs/sixth_great_lake.sunday_bridge",
  "albums/pqrs/sunshine_fix.a_spiraling_world_of_pop",
  "albums/pqrs/superthriller.the_blank_album",
  "albums/tuv/throwing_muses.doghouse--cassette",
  "albums/tuv/throwing_muses.purgatory--paradise--commentary",
  "albums/various/various.we_are_the_works_in_progress",
  "albums/various/various.mc12--a_cassette_compilation",
  "albums/various/various.cantankerous_jack_lord_feeder_operation",
  "albums/wxyz/ween.axis_bold_as_boognish",
  "albums/wxyz/ween.craters_of_the_sac",
  "christmas/albums/bob_and_tom.bob_and_tom_christmas",
  "christmas/albums/crookes.12_days_of_crookesmas",
  "christmas/albums/gloria_parker.a_toast_to_christmas",
  "christmas/albums/gloria_parker.musical_glasses_at_christmas",
  "christmas/albums/kay_martin_and_her_bodyguards.i_know_what_he_wants_for_christmas",
  "christmas/albums/ken_stanley.christmas_at_the_red_lion",
  "christmas/albums/mae_west.wild_christmas",
  "christmas/albums/sexbomb_girls.wish_ko_sa_pasko",
  "christmas/albums/slidawg_and_the_redneck_ramblers.redneck_christmas",
  "christmas/albums/three_stooges.christmas_with_the_three_stooges",
  "christmas/albums/uni_and_dr_trucker.christmas_is_the_best",
  "christmas/albums/various.a_c64_christmas",
  "christmas/albums/various.fuzz_acid_and_mistletoe-christmas_in_the_garage",
  "christmas/albums/various.xmess",
  "christmas/eps/fear.f--k_christmas",
  "christmas/eps/frank_sidebottom.christmas_is_really_fantastic_ep",
  "christmas/eps/frank_sidebottom.oh_blimey_its_christmas",
  "christmas/eps/various.the_christmas_fisting_ep",
  "classical/portsmouth_sinfonia.20_classic_rock_classics",
  "classical/portsmouth_sinfonia.classical_muddly",
  "classical/portsmouth_sinfonia.hallelujah",
  "classical/portsmouth_sinfonia.plays_the_popular_classics",
  "eps/azusa_plane--grimble_grumble.untitled",
  "eps/boyracer--american_culture.boyracer--american_culture",
  "eps/cayucas.cayocos",
  "eps/cha-cha_cohen.538_ep",
  "eps/cocteau_twins.rarities",
  "eps/crabapples.crabapples_for_change",
  "eps/das_wanderlust.the_orange_shop",
  "eps/dub_narcotic.f---k_shit_up",
  "eps/dub_narcotic.sabley_goodness",
  "eps/dub_narcotic.shake--a-puddin",
  "eps/elvira.2_big_pumpkins",
  "eps/emilys_sassy_lime.dippity_do--nut_ep",
  "eps/envelopes.sister_in_love",
  "eps/fastbacks.fastbacks",
  "eps/frank_sidebottom.franks_firm_favorites",
  "eps/frank_sidebottom.sci-fi_ep",
  "eps/james_dean_driving_experience.deans_eleventh_dream",
  "eps/juicy_eureka--azusa_plane.untitled",
  "eps/junior_varsity.go_to_the_ice_cream_social",
  "eps/lilys.returns_every_morning",
  "eps/little_frank_and_the_beastie_puppets.were_gonna_write_some_invitations",
  "eps/meat_puppets.in_a_car",
  "eps/melt-banana--locust.split_7",
  "eps/mustafa_et_monique.the_houdini_aubergine_ep",
  "eps/my_bloody_valentine.sunny_sundae_smile",
  "eps/my_bloody_valentine.the_new_record_by",
  "eps/new_bad_things.concrete",
  "eps/new_bad_things.nesting",
  "eps/new_bad_things.robin_hood",
  "eps/new_bad_things.serious_cat",
  "eps/norse_horse.grids",
  "eps/nosotrash.la_primera_maqueta",
  "eps/of_montreal--deerhoof.stygian_bisection",
  "eps/of_montreal.id_engager",
  "eps/of_montreal.jigsaw_puzzle",
  "eps/of_montreal.voltaic_crusher",
  "eps/olympic_world_of_pastelism.olympic_world_of_pastelism",
  "eps/orca_team.vancouver_bc",
  "eps/pastels.crawl_babies",
  "eps/pastels.songs_for_children",
  "eps/plouf.gojonnygogogogo_1",
  "eps/policecat.drown",
  "eps/primal_scream.crystal_crescent",
  "eps/primitives--modular.reworked_by_modular",
  "eps/primitives.new_thrills",
  "eps/puffinboy.voodoo_for_beginners",
  "eps/quickspace.amigo",
  "eps/seatman--powell.broken_folk_ep",
  "eps/shark_toys--uv-tv.shark_toys--uv-tv",
  "eps/sin_alley.lets_dance",
  "eps/someone_still_loves_you_boris_yeltsin--puzzle.sslyby_and_puzzle",
  "eps/sourpatch.mira_mija_ep",
  "eps/stars_of_the_lid.maneuvering_the_nocturnal_hum",
  "eps/sweater_girls.pretty_when_you_smile",
  "eps/various.f--k_that_weak_shit_volume_2",
  "eps/various.vindaloo_summer_special",
  "eps/velodrome_2000.charity_shopping_ep",
  "eps/velodrome_2000.sindy_sex_aid",
  "eps/vivian_girls.i_cant_stay",
  "eps/vivian_girls.tell_the_world",
  "eps/vivian_girls.wild_eyes",
]

tracks = [
  "50_pence.in_da_pub.flac",
  "50_pence.p-i-n-t.flac",
  "586.hes_got_my_measure.flac",
  "586.money_is_the_drug.flac",
  "586.saying_my_name.flac",
  "586.we_got_bored.flac",
  "additional_moog.old_computer_instrumental.flac",
  "angry_chair.i_am_the_wardrobe.flac",
  "anorak_girl.anorak_girls.flac",
  "assemblers.tribute.flac",
  "avaray.no_title.flac",
  "beachbuggy.firebird_special.flac",
  "beachbuggy.midwest.flac",
  "bette_davis_and_the_balconettes.big_pussy_sound.flac",
  "bette_davis_and_the_balconettes.shergar_the_wonder_horse.flac",
  "bette_davis_and_the_balconettes.shopping_on_the_internet.flac",
  "budget_girls.glad_all_over.flac",
  "budget_girls.pop_a_wheelie_cop_a_feelie.flac",
  "marnie.be.flac",
  "marnie.bell_jar.flac",
  "upholsteres.apple_of_my_eye",
  "urusei_yatsura.siamese--single",
  "v-vm.right_people_right_time_just_the_wrong_location",
  "v-vm.snooker_loopy--bill_werbeniuks_147_pints_mix",
  "v-vm.snooker_loopy--original",
  "velodrome_2000.rik_beckman--peel_session.flac",
]

[words]
all_caps = [
  "3cp",
  "4ad",
  "4ad3dcd",
  "a-teens",
  "a&r",
  "abba",
  "abc",
  "ac-dc",
  "acac",
  "acd",
  "afx",
  "afx2",
  "amc",
  "blazar",
  "bbc",
  "bbc2",
  "bf",
  "bmr",
  "bmx",
  "bnoc",
  "brkn01",
  "brkn02",
  "brkn03",
  "bs",
  "bt",
  "bv",
  "bwv",
  "ckid",
  "csi",
  "cv",
  "cvb",
  "dc",
  "dj",
  "dlp",
  "dva",
  "emi",
  "ep",
  "fb",
  "fbi",
  "fc",
  "fm",
  "gb",
  "gf",
  "gnac",
  "gq",
  "gr",
  "gsg",
  "gsoh",
  "gtg",
  "gunquit",
  "hc",
  "hiv",
  "hp",
  "hwv",
  "ihop",
  "isan",
  "isbn",
  "itv",
  "jc",
  "jdp",
  "jlh",
  "jt",
  "jxl",
  "kaos",
  "kb",
  "kfc",
  "kg",
  "klf",
  "km",
  "kmfdm",
  "krk",
  "kvrx",
  "l&m",
  "l.a.",
  "lcd",
  "lp",
  "lp2",
  "lsd",
  "lsxx",
  "m/a/r/r/s",
  "mbv",
  "mc",
  "mc5",
  "mdma",
  "mf",
  "mj",
  "mp3",
  "mtv",
  "nato",
  "nme",
  "npl",
  "nw",
  "nyc",
  "nypd",
  "od",
  "oh!",
  "olv",
  "omd",
  "ost",
  "ox4",
  "pbm",
  "pcm",
  "pcp",
  "pm",
  "psb",
  "qed",
  "qrj",
  "qwerty",
  "r&b",
  "rm",
  "scsi",
  "sh",
  "sm",
  "sm57",
  "spoc",
  "tda",
  "tko",
  "tm",
  "tnt",
  "tr",
  "ts",
  "tv",
  "tvc",
  "tvr17",
  "tx",
  "tyo",
  "ufo",
  "uk",
  "ulc",
  "urc",
  "usa",
  "usm",
  "uv",
  "uvtv",
  "vip",
  "vsx",
  "vv",
  "vvv",
  "wiaiwya",
  "wkrp",
  "wmc",
  "wr",
  "ww3",
  "xr3",
  "zz",
]

no_caps = [
  "bis",
  "bloweyelashwish",
  "case/lang/viers",
  "der",
  "kd",
  "lang",
  "lovesliescrushing",
  "und",
]

ignore_case = [
  "5-6-7-8's",
  "'a:'",
  "b's",
  "bittonic",
  "ça",
  "d'arby",
  "d'isan",
  "d'or",
  "eps",
  "hearts!attack",
  "iiia",
  "iiib",
  "lps",
  "mcalmont",
  "mcbride",
  "mccarthy",
  "mccartney",
  "mccay",
  "mccombs",
  "mccoy",
  "mcculloch",
  "mcdonalds",
  "mcfly",
  "mcgee",
  "mcintyre",
  "mclusky",
  "mccluskey",
  "melt-banana",
  "mms",
  "mxbx",
  "o'keefe",
  "tjam",
  "tatu",
  "us",
  "v/vm",
  "x",
]

[words.expand]
"add_n_to_x" = "Add N to (X)"
"add_n_to_fuxa" = "Add N to Fü(x)a"
"fuxa" = "Füxa"
