foreground             #5c666d
background             #efeded
selection_foreground   #000000
selection_background   #b6d7ea
url_color              #7170C2

# white
color0                 #ffffff
color8                 #bac2c6

# red
color1                 #92301c
color9                 #ba452e

# green
color2                 #22754e
color10                #22754e

# yellow
color3                 #a08214
color11                #a08214

# blue
color4                 #276589
color12                #b6d7ea

# magenta
color5                 #845db7
color13                #7170C2

# cyan
color6                 #6da7ce
color14                #000000

# black
color7                 #000000
color15                #5c666d
