include ${KITTY_OS}.conf
include current-theme.conf

cursor #888888
cursor_text_color #ffffff
cursor_shape underline
cursor_shape_unfocused hollow
cursor_underline_thickness 2.0
cursor_blink_interval 0.5 
cursor_stop_blinking_after 15.0

url_style straight

disable_ligatures always

enable_audio_bell no
progress_bar top
scrollback_lines 5000
# repaint_delay 4

copy_on_select clipboard

initial_window_width  80c
initial_window_height 40c
remember_window_size no

confirm_os_window_close 0

tab_bar_edge bottom            
tab_bar_min_tabs 1             
tab_title_max_length 32        
tab_bar_style slant
active_tab_foreground   #000000
active_tab_background   #efeded
inactive_tab_foreground #5c666d
inactive_tab_background #999999
tab_bar_background      #bac2c6
active_tab_font_style   bold
inactive_tab_font_style italic


window_padding_width 0 0 7.5 0

inactive_text_alpha 0.8

map ctrl+shift+insert paste_from_clipboard
map shift+insert      paste_from_selection
map ctrl+shift+up     scroll_to_prompt -1
map ctrl+shift+down   scroll_to_prompt 1

mouse_map left click ungrabbed discard_event

# font_family      family='Berkeley Mono Variable'
font_family      family='IBM Plex Mono'
bold_font        auto
italic_font      auto
bold_italic_font auto
